sudo: required

services:
  - docker

script:
  - docker build -t docker-httpd-ssl-balancer .
  - docker run -d --name docker-httpd-ssl-balancer docker-httpd-ssl-balancer && sleep 10 && docker logs docker-httpd-ssl-balancer && docker stop docker-httpd-ssl-balancer && docker rm docker-httpd-ssl-balancer

